### ISSUE TITLE
asking for some enhancement

### ISSUE THREAD

**Issue by hatem-noureddine** [onjin/mkchangelog#15]
- Jinja tempalte enhancement:
Can you improve the way that we can customize the jinja template like exposing a filter to replace using regex.
some thing like:
{{ change | regex_replace('#(\d+)', '[#$1](https://github.com/xxxx/pull/$1)') }}

- list enhancement
in the settings, can we have a regex to filter which scope we want to show ?

**Comment by onjin** [comment]
Hey, sure.

Regexps will be a good enhancement. I can get on it probably during weekend.

**Comment by onjin** [comment]
So far I've added `regex_replace` in version 2.3.3 :)

**Comment by onjin** [comment]
For scope filtering I've added hooks system to filter LogLines using python. It's available from version 2.4.0

- https://github.com/onjin/mkchangelog#plugins--hooks-system <- description
- https://github.com/onjin/mkchangelog/blob/master/.mkchangelog.d/hooks.py#L20 <- example hook for scope filtering

**Comment by onjin** [comment]
Also, using hooks.py you can now add (or replace) any jinja templates filter:
 - https://github.com/onjin/mkchangelog/blob/master/.mkchangelog.d/hooks.py#L16

**Comment by onjin** [comment]
I'm closing this enhancement, as I think all cases can be covered right now. Thank you for your suggestions :)
