### ISSUE TITLE
allow users to show a template commit message that leverages best use cases of writing a meaningfull commit messages

### ISSUE THREAD

**Issue by marcinkuzminski** [onjin/mkchangelog#8]
I'd would be great to have a command that "showcases" what you can write inside a commit message for mkchangelog to fully leverage git commit text.

Right now to start it's a bit unclear how commit messages in git should be written so the generated changelog is using a lot of features.

maybe something like `mkchangelog example-commit` ?

**Comment by onjin** [comment]
Since version `1.4.0` you can use `mkchangelog commit [--stdout]` command.

Without `--stdout` option the `message.txt` file will be written, so then you can edit it or just run`git commit -F message.txt` to use it.
```console
$ mkchangelog commit --stdout
Git Commit Format: type(scope): summary

Commit Type [build,chore,ci,dev,docs,FEAT,fix,perf,refactor,style,test,translations]: feat
Scope: (optional): commands
Summary line: add `mkchangelog commit` command to generate proper commit message
Is breaking change? [y/N]
Long description (body): The message be displayed at stdout by passing `--stdout` parameter. Otherwise will be saved as `message.txt` file.
---
feat(commands): add `mkchangelog commit` command to generate proper commit message

The message be displayed at stdout by passing `--stdout` parameter. Otherwise will be saved as `message.txt` file.
---
```

**Comment by marcinkuzminski** [comment]
ohh, really nice !
